### ISSUE TITLE
Update to MYSQL 8

### ISSUE THREAD

**Issue by stefanneuhaus** [stefanneuhaus/dependencycheck-central-mysql-docker#12]
MYSQL 5 is still supported and maintained, nevertheless the goal is to migrate to the most recent stable release version of MYSQL 8. 

Though MYSQL 8 is expected to have an edge over MYSQL 5 in terms of performance, what I observe is the exact opposite: switching from MYSQL 5.7.31 to 8.0.25 the time for the initial database update went up from1,5 h to 3 h.

This seems to need some tweaking of the configuration, indexes, or queries. Help from MYSQL experts is much appreciated.

**Comment by Jurrie** [comment]
Pull request #19 will do this bump. The initial synchronization was `BUILD SUCCESSFUL in 54m 17s`. I am not sure how long the initial synchronization took on MySQL 5.x though, so I can't compare.

**Comment by stefanneuhaus** [comment]
PR #19 has been merged in the meantime. Initial sync time was ~50min on my machine, which is comparable to the runtime with MySQL 5. I did not do the actual comparison because with MySQL5 I ran into #18. In the end the runtime is fine anyway and the update to MySQL 8 had to be done soner or later.
