### ISSUE TITLE
Gradle kotlin DSL not recognizing postgres driver

### ISSUE THREAD

**Issue by senthilnathanrajendran** [stefanneuhaus/dependencycheck-central-mysql-docker#17]
Can you please let me know how to add postgres driver in kotlin DSK Gradle

**Comment by stefanneuhaus** [comment]
@senthilnathanrajendran I am wondering what this issue is about. Is this an actual problem with this project? Or are you having difficulties consulting the Gradle documentation?

**Comment by nauni77** [comment]
> Can you please let me know how to add postgres driver in kotlin DSK Gradle

At this project is no postgres used and because of this there is IMHO no need to add a postgres driver. I don't understand this ticket too.
