### ISSUE TITLE
DependencyCheck 10.0 requires a new DB schema

### ISSUE THREAD

**Issue by sergeykad** [stefanneuhaus/dependencycheck-central-mysql-docker#22]
From the release notes:

Fixed the NVD API related errors by adding cvssV4 support (#6756)
breaking changes: anyone utilizing a centralized database will need to upgrade the schema; see changes in [PR #6756](https://github.com/jeremylong/DependencyCheck/pull/6756/files#diff-ca432c4b41d39caa84d140e06694b09c7e6394c8a2db72ba27516dc77ee3bd67)

https://github.com/jeremylong/DependencyCheck/blob/main/CHANGELOG.md#change-log

**Comment by stefanneuhaus** [comment]
Published the new 10.0.1 release to DockerHub
